### ISSUE TITLE
DLM doesn't seem to work, am I doing something wrong?

### ISSUE THREAD

**Issue by JHurk** [mcartoixa/synology-dlm-rarbg#1]
I installed the DLM by downloading the latest version and adding it in Download Station.
Searching doesn't bring any results, only BT search engine active is rarbg. When I activate other engines like 1337x and Bitsoup I do get results.

Same happens when I add the DLM for TPB, also no results.
Correction; TPB does give results. Only rarbg doesn't work

Does this plugin still work? Am I doing something wrong? Thanks!

**Comment by mcartoixa** [comment]
Thanks for your feedback.

The plugin does not seem to work for me either, and I suspect RARBG is blocking the activity of the plugin with a CAPTCHA ([depending on your IP address](https://www.reddit.com/r/torrents/comments/688szr/rarbg_constantly_demanding_i_fill_out_captchas_is/)) DLM plugins are difficult to debug, and if my suspicions are correct there is not much I can do for now...

If you have the means to test the plugin at home in dev mode (cf. [dlm/tests/querier.php](https://github.com/mcartoixa/synology-dlm-rarbg/blob/master/dlm/tests/querier.php)) you might be able to get more information. I'll try myself.

**Comment by JHurk** [comment]
Sorry, would like to help but have no knowledge in how to test this in dev mode.

It would surprise me if there was a CAPTCHA issue because I never get a CAPTCHA when I browser RARBG. So I would say my home IP (static) would not cause a CAPTCHA.

Hope you find something when you look into it/try yourself. Thanks.

**Comment by mcartoixa** [comment]
Their API seems to have changed: https://torrentapi.org/pubapi_v2.php?get_token=get_token now returns an error. It did (and should ?) not: https://torrentapi.org/apidocs_v2.txt

**Comment by mcartoixa** [comment]
Version 1.2 works much better than version 1.1 😉
Beware though: the RARBG API is **very** limited (only 1 call every 2s), and I suspect this rate will be shared by every user of the plugin. This will do for now, though.

**Comment by JHurk** [comment]
Great! Thanks it is fixed indeed in 1.2.14
