### ISSUE TITLE
Module not working

### ISSUE THREAD

**Issue by kpantos** [mcartoixa/synology-dlm-rarbg#3]
Downloaded the latest version of the module and installed it on dsm.
However, searching through BT search is not bringing back any results.
Any ideas?

**Comment by mcartoixa** [comment]
Thanks for reporting. Maybe the API stopped responding? Or maybe the package was changed.
I will  try and take a look, but unfortunately I stopped using my Synology for downloads so I don't think I will be able to test in case the package was changed.

**Comment by mcartoixa** [comment]
It appears that the API does not seem to have been changed, and the module works fine on my Synology.
![image](https://user-images.githubusercontent.com/1251985/148687723-6977c111-1c72-492a-8af1-384f85af2e05.png)

I will close the issues, but do not hesitate to come back to me with more information. Also, try to access the API directly from your IP address (cf. https://torrentapi.org/apidocs_v2.txt?app_id=gaia for the documentation).
